version: '3.8'

services:
  dev-db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: ImAPassword
      POSTGRES_DB: nestjs
  test-db:
    image: postgres:13
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: ImAPassword
      POSTGRES_DB: nestjs
